# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18c20e6d3bec3f89ecfe1145563bfbd4280ce746f29939d184453157a75f65c173c54594b0bf1e039a8c10d72a46c63a949f1a4f7d2a9c9a4ba230b1c46e6d5c

test:
  secret_key_base: 660b82ee700141f89ee1debaccf92ed6ab58ad77094597c649dbb5aa9bd96d1397e134c5610ba7c9982ab6e3525cf7f725a8ffe24a4ae1526f5836d28cca43e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
